###############################################################################
# Variables
###############################################################################
CORE             ?= core
PARAMS           ?= 
OUTPUT_DIR       ?= verilated
SRC_DIR          ?= ../src_v
SRC_TYPE         ?= v
SRC_V_DIR        ?= ../src_v
OUTPUT_SUFFIX    ?=
SRC              ?= riscv_tcm_top
NAME             ?= riscv_tcm_top

RTL_INCLUDE       = ../../core/$(CORE)

# Verilator options
# --trace-max-array: default in V5.x is too low to capture the 16K-entry TCM
# ram. Bumping it lets ram[N] show up in GTKWave under u_tcm.u_ram.
VERILATE_PARAMS  ?= --trace --trace-max-array 16384
VERILATOR_OPTS   ?= --pins-sc-uint

OLDER_VERILATOR := $(shell verilator --l2-name v 2>&1 | grep "Invalid Option" | wc -l)

ifeq ($(OLDER_VERILATOR),0)
  VERILATOR_OPTS += --l2-name v
endif

TARGETS          ?= $(OUTPUT_DIR)/V$(NAME)

###############################################################################
# Rules
###############################################################################
all: $(TARGETS)

$(OUTPUT_DIR):
	mkdir -p $@

$(OUTPUT_DIR)/V$(NAME): $(SRC_DIR)/$(SRC).$(SRC_TYPE) | $(OUTPUT_DIR)
	verilator --sc $(patsubst $(OUTPUT_DIR)/V$(NAME), $(SRC_V_DIR)/$(NAME), $@) --Mdir $(OUTPUT_DIR) -I./$(SRC_V_DIR) $(patsubst %,-I%,$(RTL_INCLUDE)) $(VERILATOR_OPTS) $(VERILATE_PARAMS)

clean:
	rm -rf $(TARGETS) $(OUTPUT_DIR)
